## Example Config file
baseURL: "https://sante-afk.github.io/sante-homepage/"
theme: "terminalcv"
title: "terminalcv"

params:
  version: "2.0.0"
  description: "My terminal cv"
  blog: true
  prompt:
    core:
      text: "user@terminalCV"
      color: "default"
      before: "["
      beforeColor: "red"
      after: '\]'
      afterColor: "red"
      # separator: '-'
    separator:
      text: "-"
      # color:
    path:
      before: "["
      beforeColor: "red"
      text: "~/terminalcv"
      color: "blue"
      after: '\]'
      afterColor: "red"
    extra:
      text: ": "
      color: "orange"

  # promptColor: grey
  # promptSimbols: ":~$"
  # promptSimbolsColor: grey
  # startxLocation: https://example.com
  # useLess: true
  listLS: true
  #exitLocation: "about:blank"
  exitMessage: "[Session completed, the browserwindow can be safely closed]"
  source: true
  #use a ‎ (blank character) if your first character of the ascii art is a whitespace
  greeting: |
    ‎
                           ▄                           ▄▀▀  █     
     ▄▄▄    ▄▄▄   ▄ ▄▄   ▄▄█▄▄   ▄▄▄           ▄▄▄   ▄▄█▄▄  █   ▄ 
    █   ▀  ▀   █  █▀  █    █    █▀  █         ▀   █    █    █ ▄▀  
     ▀▀▀▄  ▄▀▀▀█  █   █    █    █▀▀▀▀   ▀▀▀   ▄▀▀▀█    █    █▀█   
    ▀▄▄▄▀  ▀▄▄▀█  █   █    ▀▄▄  ▀█▄▄▀         ▀▄▄▀█    █    █  ▀▄ 

    Welcome to my online resume

    Type 'help' for a list of available commands

  bootsequence: |
    User request detected
    Reserving Cloud Resources
    ............................
    Cloud Network ready
    ........
    Cloud Instance ready
    .......................
    Internet Breakout Ready, but Pong is preferred 

    Inititating CloudOS
    CloudOS Kernel Version 1.4.2: Sat February 29 23:21:41 CEST 2025; root:xnu-1699.22.73~1/RELEASE_ARM_64
    Loglevel = quiet
    ......
    ............
    ..................
    ........................
    ..............................
    ....................................

    Copyright 1979, 1980, 1983, 1986, 1988, 1989, 1991, 1992, 1993, 1994
    The Regents of the University of California. All rights reserved.

    Copyright 2024, 2025
    TerminalCV. MIT License (MIT)

    [CloudOSBoot1]: ready
    [CloudOSBoot2]: ready
    [Webserver]: ready 
    [HUGO]: ready
    [TerminalCV]: ready

    Boot Complete, accepting user input.

  whois:
    # settings:
    #   useLess: true
    details:
      name: "Mikhail Smirnov"
      profession: "junior frontend developer"
      location: "Yaroslavl"
      email: "musa62298@gmail.com"
      homelink: "https://sante-afk.github.io/sante-homepage/"
      description: |
        Hi! I’m a beginner frontend developer 
        passionate about creating modern and 
        user-friendly web interfaces.

  social:
    # settings:
    #   useLess: true
    #   hideName: true
    details:
      - name: "github"
        url: "https://github.com/sante-afk"
      - name: "LinkedIn"
        url: "https://www.linkedin.com/in/mikhail-smirnov-00bb8b36a/"
      - name: "Telegram"
        url: "https://t.me/Qttrehbfjkkkjkjj"
      - name: "SoundCloud"
        url: "https://soundcloud.com/4543689"

  work:
    # settings:
    #   useLess: true
    details:
      - jobTitle: Frontend Web Developer
        color: red
        company: "Zentip"
        location: Moscow region, Odintsovo
        date: June 2025 - Present
        description: Development and support of user interfaces of corporate web applications using SAPUI5, JavaScript, XML for building UI and ABAP for implementing business logic on the server side.

  education:
    details:
      - courseName: Yaroslavl State Technical University
        date: Sept 2022 - 2026
        #description: There is no need for description

  skills:
    settings:
      useLess: true
    details:
      - name: JavaScript
        color: red
        percentage: 90
        # Description: you can add a description

      - name: sapui5
        color: default
        percentage: 50

      - name: XML
        color: default
        percentage: 50
        # description: Skill names can have colors too
      
  softskills:
    # settings:
    #   useLess: true
    details:
      - name: Communication 
        color: default
        percentage: 20
        #description:

      - name: Teamwork
        color: red
        percentage: 90
        # description: Description

  languages:
    # settings:
    #   useLess: true
    details:
      - name: English
        color: Blue
        percentage: 50
        #description:

      - name: Russian
        color: Blue
        percentage: 50
        #description:

      - name: Gibberish
        percentage: 100
        description: pasghettipigglywiggly

  projects:
    # settings:
    #   useLess: true
    details:
      # - title: Project Red
      #   color: red
      #   date: since 2019
      #   link: https://example.com
      #   description: Describing red stuff

      # - title: Project Blue
      #   color: blue
      #   date: since 2016
      #   link: https://example.com/blue
      #   #description: nothing to describe

      # - title: Project Default
      #   date: Since 2017
      #   link: https://example.com/default
      #   #description: not there either

  certifications:
    # settings:
    #   useLess: true
    details:
      - certName: Certificate for organizing a school for developing soft skills
        company: Yaroslavl State Technical University 
        date: 2023
        badge: https://www.linkedin.com/in/mikhail-smirnov-00bb8b36a/
        #description: Lorem Ipsum

  # misc:
  #   # settings:
  #   #   useLess: true
  #   commandName: newcommand
  #   title: "This Section can have a different command name"
  #   titleColor: teal
  #   content: |
  #     Here the title and the content can have different colors
  #     The content can be multi

  #     line

  #     And spaces       will be respected as well
  #     This section will have the default command: misc
  #     but you can name it something else with the property
  #     commandName: <String>
  #     Give it a shot and try and uncomment the line 
  #     commandName: newcommand
  #     now instead of misc you can execute the newcommand for this section
  #     Auto completion will know it too! :D

  #   contentColor: orange
